"""progval/irctest controller for dsc-ircd.

Usage (from an irctest checkout, with this directory on PYTHONPATH)::

    export IRCTEST_DSC_IRCD=/path/to/target/debug/ircd
    pytest --controller dsc_ircd -m '…' …

See docs/IRCTEST.md for the curated marker set and unsupported allowlist.
"""

from __future__ import annotations

import os
import shutil
from pathlib import Path
from typing import Optional, Set, Type

from irctest.basecontrollers import BaseServerController, DirectoryBasedController
from irctest.runner import NotImplementedByController
from irctest.specifications import Capabilities, OptionalBehaviors

# Keep in sync with crates/ircd/src/session/cap.rs BASE_CAPS (+ SASL when accounts on).
# Do not declare caps here that the binary does not advertise.
ADVERTISED_CAPS = frozenset(
    (
        Capabilities.ACCOUNT_TAG,
        Capabilities.BATCH,
        Capabilities.MESSAGE_TAGS,
        Capabilities.SERVER_TIME,
    )
)

TEMPLATE_CONFIG = """\
# Generated by tools/irctest/dsc_ircd.py for progval/irctest.
# Server name must match irctest expectations (PONG / 001 source).

[server]
name = "My.Little.Server"
motd = "dsc-ircd irctest"
admin_name = "irctest"
admin_email = "irctest@example.com"
max_nick_length = 32
max_channel_length = 64

[[listen]]
bind = "{hostname}:{port}"
tls = {tls_bool}
{tls_paths}

[oper]
enabled = true
name = "operuser"
password = "operpassword"

[history]
enabled = false

[limits]
max_clients = 256
max_clients_per_ip = 256
flood_lines_per_window = 1000
flood_window_secs = 10
"""


class DscIrcdController(BaseServerController, DirectoryBasedController):
    software_name = "dsc-ircd"
    supported_sasl_mechanisms: Set[str] = set()
    supports_sts = False
    _port_wait_interval = 0.05

    capabilities = ADVERTISED_CAPS

    optional_behaviors = frozenset(
        (
            OptionalBehaviors.CAP_REQ_MINUS,
        )
    )

    def create_config(self) -> None:
        super().create_config()
        with self.open_file("ircd.toml"):
            pass

    def _binary(self) -> Path:
        env = os.environ.get("IRCTEST_DSC_IRCD")
        if env:
            p = Path(env)
            if p.is_file() and os.access(p, os.X_OK):
                return p
            raise RuntimeError(f"IRCTEST_DSC_IRCD is not an executable file: {env}")
        which = shutil.which("ircd")
        if which:
            return Path(which)
        raise RuntimeError(
            "Set IRCTEST_DSC_IRCD to the dsc-ircd binary "
            "(e.g. $REPO/target/debug/ircd) or put `ircd` on PATH."
        )

    def run(
        self,
        hostname: str,
        port: int,
        *,
        password: Optional[str],
        ssl: bool,
        run_services: bool,
        faketime: Optional[str],
        websocket_hostname: Optional[str],
        websocket_port: Optional[int],
    ) -> None:
        if websocket_hostname is not None or websocket_port is not None:
            raise NotImplementedByController("Websocket")
        if password is not None:
            raise NotImplementedByController("Password")
        if run_services:
            raise NotImplementedByController("Services")
        if faketime and shutil.which("faketime"):
            # dsc-ircd does not need faketime for the curated set; ignore gently.
            pass

        assert self.proc is None
        self.port = port
        self.hostname = hostname
        self.create_config()
        assert self.directory

        tls_bool = "true" if ssl else "false"
        tls_paths = ""
        if ssl:
            self.gen_ssl()
            tls_paths = f'cert = "{self.pem_path}"\nkey = "{self.key_path}"\n'

        with self.open_file("ircd.toml", "w") as fd:
            fd.write(
                TEMPLATE_CONFIG.format(
                    hostname=hostname,
                    port=port,
                    tls_bool=tls_bool,
                    tls_paths=tls_paths,
                )
            )

        data_dir = self.directory / "data"
        data_dir.mkdir(exist_ok=True)

        cmd = [
            str(self._binary()),
            "--config",
            str(self.directory / "ircd.toml"),
        ]
        self.proc = self.execute(cmd, cwd=str(self.directory))
        self.wait_for_port()


def get_irctest_controller_class() -> Type[DscIrcdController]:
    return DscIrcdController
